import { useEffect, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Api } from '../../api/client'
import type { EventEmailKind, EventEmailPlaceholder, EventEmailTemplate, EventEmailWording } from '../../api/types'

type Field = keyof EventEmailWording

function errMsg(e: any): string {
  const d = e?.response?.data
  return typeof d === 'string' ? d : d?.title || e?.message || 'Error'
}

/** Settings → Event emails: edit the wording of the automatic "new event" / "event updated"
 *  emails in English and Spanish, with a live preview. The details, change list and answer
 *  buttons are generated by the server and can't be removed. */
export function EventEmailsSection({
  onError,
  onNotice,
}: {
  onError: (e: string | null) => void
  onNotice: (n: string | null) => void
}) {
  const { t, i18n } = useTranslation()
  const [templates, setTemplates] = useState<EventEmailTemplate[] | null>(null)
  const [placeholders, setPlaceholders] = useState<EventEmailPlaceholder[]>([])
  const [kind, setKind] = useState<EventEmailKind>(0)
  const [language, setLanguage] = useState(0)
  const [draft, setDraft] = useState<EventEmailWording>({ subject: '', message: '', footer: '' })
  const [saving, setSaving] = useState(false)
  const [preview, setPreview] = useState<{ subject: string; html: string } | null>(null)

  // Placeholder chips insert into whichever field was focused last, at the cursor.
  const lastField = useRef<Field>('message')
  const refs = {
    subject: useRef<HTMLInputElement>(null),
    message: useRef<HTMLTextAreaElement>(null),
    footer: useRef<HTMLTextAreaElement>(null),
  }

  const current = templates?.find(x => x.kind === kind && x.language === language) ?? null
  const dirty = !!current && (draft.subject !== current.subject || draft.message !== current.message || draft.footer !== current.footer)

  // Load once. (The parent passes a new onError each render, so it can't be a dependency.)
  useEffect(() => {
    Api.eventEmailTemplates()
      .then(r => { setTemplates(r.templates); setPlaceholders(r.placeholders) })
      .catch(e => onError(errMsg(e)))
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // Show the saved wording whenever the selected email changes.
  useEffect(() => {
    if (current) setDraft({ subject: current.subject, message: current.message, footer: current.footer })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [kind, language, templates])

  // Live preview, debounced so typing doesn't send a request per keystroke.
  useEffect(() => {
    if (!current) return
    const handle = setTimeout(() => {
      Api.previewEventEmail(kind, language, draft).then(setPreview).catch(() => setPreview(null))
    }, 400)
    return () => clearTimeout(handle)
  }, [draft, kind, language, current])

  const select = (k: EventEmailKind, l: number) => {
    if (k === kind && l === language) return
    if (dirty && !window.confirm(t('admin.evtEmailDiscardConfirm'))) return
    setKind(k)
    setLanguage(l)
  }

  const insert = (key: string) => {
    const field = lastField.current
    const el = refs[field].current
    const token = `{${key}}`
    const value = draft[field]
    const start = el?.selectionStart ?? value.length
    const end = el?.selectionEnd ?? value.length
    setDraft({ ...draft, [field]: value.slice(0, start) + token + value.slice(end) })
    // Put the cursor right after the inserted placeholder.
    requestAnimationFrame(() => {
      if (!el) return
      el.focus()
      el.setSelectionRange(start + token.length, start + token.length)
    })
  }

  const replaceTemplate = (updated: EventEmailTemplate) =>
    setTemplates(list => list?.map(x => (x.kind === updated.kind && x.language === updated.language ? updated : x)) ?? null)

  const save = async () => {
    setSaving(true)
    onError(null)
    try {
      replaceTemplate(await Api.saveEventEmailTemplate(kind, language, draft))
      onNotice(t('admin.evtEmailSaved'))
    } catch (e) {
      onError(errMsg(e))
    } finally {
      setSaving(false)
    }
  }

  const reset = async () => {
    if (!current || !window.confirm(t('admin.evtEmailResetConfirm'))) return
    setSaving(true)
    onError(null)
    try {
      await Api.resetEventEmailTemplate(kind, language)
      replaceTemplate({
        ...current, isCustom: false, updatedAt: null, updatedBy: null,
        subject: current.defaultSubject, message: current.defaultMessage, footer: current.defaultFooter,
      })
      onNotice(t('admin.evtEmailResetDone'))
    } catch (e) {
      onError(errMsg(e))
    } finally {
      setSaving(false)
    }
  }

  if (!templates) return <div className="text-sm text-slate-500">{t('common.loading')}</div>

  const pill = (active: boolean) =>
    `px-3 py-1.5 text-sm rounded-md border ${active
      ? 'bg-emerald-700 border-emerald-700 text-white'
      : 'bg-white border-slate-300 text-slate-700 hover:bg-slate-50'}`
  const status = (k: EventEmailKind, l: number) => templates.find(x => x.kind === k && x.language === l)?.isCustom
  const spanishUi = i18n.language?.startsWith('es')

  return (
    <div className="space-y-4">
      <p className="text-sm text-slate-600">{t('admin.evtEmailBlurb')}</p>

      <div className="flex flex-wrap gap-4">
        <div className="flex gap-2">
          <button className={pill(kind === 0)} onClick={() => select(0, language)}>{t('admin.evtEmailNew')}</button>
          <button className={pill(kind === 1)} onClick={() => select(1, language)}>{t('admin.evtEmailUpdated')}</button>
        </div>
        <div className="flex gap-2">
          {[0, 1].map(l => (
            <button key={l} className={pill(language === l)} onClick={() => select(kind, l)}>
              {l === 0 ? t('admin.evtEmailEnglish') : t('admin.evtEmailSpanish')}
              {status(kind, l) && <span className="ml-1" aria-hidden>●</span>}
            </button>
          ))}
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <div className="space-y-3 min-w-0">
          <div className="text-xs text-slate-500">
            {dirty
              ? <span className="text-amber-700 font-medium">{t('admin.evtEmailUnsaved')}</span>
              : current?.isCustom && current.updatedAt
                ? t('admin.evtEmailCustom', { when: new Date(current.updatedAt).toLocaleString() }) + (current.updatedBy ? ` · ${current.updatedBy}` : '')
                : t('admin.evtEmailDefault')}
          </div>

          <label className="block text-sm">
            <span className="text-slate-700 font-medium">{t('admin.evtEmailSubject')}</span>
            <input
              ref={refs.subject}
              value={draft.subject}
              maxLength={256}
              onFocus={() => { lastField.current = 'subject' }}
              onChange={e => setDraft({ ...draft, subject: e.target.value })}
              className="mt-1 w-full border border-slate-300 rounded-md px-2 py-1.5 text-sm"
            />
          </label>

          <label className="block text-sm">
            <span className="text-slate-700 font-medium">{t('admin.evtEmailMessage')}</span>
            <textarea
              ref={refs.message}
              value={draft.message}
              rows={7}
              maxLength={4000}
              onFocus={() => { lastField.current = 'message' }}
              onChange={e => setDraft({ ...draft, message: e.target.value })}
              className="mt-1 w-full border border-slate-300 rounded-md px-2 py-1.5 text-sm font-mono"
            />
          </label>

          <label className="block text-sm">
            <span className="text-slate-700 font-medium">{t('admin.evtEmailFooter')}</span>
            <textarea
              ref={refs.footer}
              value={draft.footer}
              rows={3}
              maxLength={2000}
              onFocus={() => { lastField.current = 'footer' }}
              onChange={e => setDraft({ ...draft, footer: e.target.value })}
              className="mt-1 w-full border border-slate-300 rounded-md px-2 py-1.5 text-sm font-mono"
            />
          </label>

          <div>
            <div className="text-xs text-slate-500 mb-1">{t('admin.evtEmailPlaceholders')}</div>
            <div className="flex flex-wrap gap-1.5">
              {placeholders.map(p => (
                <button
                  key={p.key}
                  type="button"
                  title={`{${p.key}}`}
                  // Keep focus (and the cursor) in the field being edited.
                  onMouseDown={e => e.preventDefault()}
                  onClick={() => insert(p.key)}
                  className="text-xs px-2 py-1 rounded border border-emerald-200 bg-emerald-50 text-emerald-800 hover:bg-emerald-100"
                >
                  {spanishUi ? p.labelEs : p.labelEn}
                </button>
              ))}
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-3 pt-1">
            <button
              onClick={save}
              disabled={saving || !dirty || !draft.subject.trim() || !draft.message.trim()}
              className="bg-emerald-700 text-white text-sm font-semibold px-4 py-2 rounded-md hover:bg-emerald-800 disabled:opacity-60"
            >
              {t('admin.evtEmailSave')}
            </button>
            {current?.isCustom && (
              <button onClick={reset} disabled={saving} className="text-sm text-slate-600 hover:underline">
                {t('admin.evtEmailReset')}
              </button>
            )}
          </div>
        </div>

        <div className="min-w-0">
          <div className="text-sm font-medium text-slate-700">{t('admin.evtEmailPreview')}</div>
          <p className="text-xs text-slate-500 mb-2">{t('admin.evtEmailPreviewNote')}</p>
          {preview && (
            <div className="border border-slate-200 rounded-md overflow-hidden">
              <div className="bg-slate-50 border-b border-slate-200 px-3 py-2 text-sm">
                <span className="text-slate-500">{t('admin.evtEmailSubject')}: </span>
                <span className="font-medium text-slate-800">{preview.subject}</span>
              </div>
              {/* Empty sandbox: the preview can't run scripts or navigate this page. */}
              <iframe title={t('admin.evtEmailPreview')} sandbox="" srcDoc={preview.html} className="w-full h-[640px] bg-white" />
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
